import { coupeDepuisMaquette, planDepuisMaquette } from '../canvas/maquette'
import type { Projet } from './types'

/**
 * Les huit projets, dans l'ordre de l'index. Contenu placeholder : chaque
 * fiche est réaliste mais fictive. Les images sont des SVG générés par
 * `scripts/generate-la-coupe-placeholders.ts` à partir de cette liste.
 */
export const projets: Projet[] = [
  {
    slug: 'maison-des-vignes',
    titre: 'Maison des Vignes',
    lieu: 'Meursault, Bourgogne',
    annee: 2023,
    surface: 186,
    programme: 'Maison individuelle',
    categorie: 'Logement',
    statut: 'Livré',
    maitriseOuvrage: 'Privée',
    equipe: ['Atelier Mireille Vasseur', 'Structure : Batiserf', 'Paysage : Coloco'],
    texte:
      "Une maison longue posée sur la pente, entre les vignes et le village. Le rez-de-chaussée en pierre de Comblanchien s'enfonce dans le talus et porte un étage en ossature bois, décalé d'une travée vers le sud pour ouvrir une terrasse couverte. Un *vide traversant* relie la cuisine au grenier et laisse descendre la lumière du nord sur l'escalier. Les menuiseries en chêne, les enduits à la chaux et le zinc du toit sont les seuls matériaux visibles. La maison chauffe avec un poêle de masse et une ventilation double flux ; l'inertie de la pierre fait le reste. Elle a été dessinée pour être *habitée longtemps*, puis divisée sans travaux lourds.",
    images: [
      { ratio: '3:2', alt: 'Façade sud de la Maison des Vignes, étage bois en surplomb sur la terrasse' },
      { ratio: '4:5', alt: "L'escalier dans le vide traversant, lumière du nord" },
      { ratio: '16:9', alt: 'Vue depuis les vignes, la maison dans la pente au crépuscule' },
      { ratio: '3:2', alt: 'Cuisine, plan de travail en pierre et menuiseries chêne' },
      { ratio: '1:1', alt: 'Détail de la rive de toit en zinc' },
      { ratio: '3:2', alt: 'Chambre sous les combles, fenêtre de toit' },
      { ratio: '4:5', alt: 'Mur en pierre de Comblanchien au ras du talus' },
      { ratio: '16:9', alt: 'Terrasse couverte, vue sur le village' },
    ],
    // Le projet phare est aussi la maquette du hero : plan et coupe en dérivent.
    dessins: [
      planDepuisMaquette(
        [
          [6, 0, 6, 11],
          [6, 5.5, 18, 5.5],
          [12, 5.5, 12, 11],
          [0, 4, 6, 4],
        ],
        [[7, 11], [13, 17]],
        'Plan du rez-de-chaussée',
      ),
      coupeDepuisMaquette('Coupe transversale sur le vide'),
    ],
    teinte: 34,
  },
  {
    slug: 'halle-saint-ouen',
    titre: 'Halle Saint-Ouen',
    lieu: 'Saint-Ouen-sur-Seine',
    annee: 2022,
    surface: 2400,
    programme: 'Réhabilitation d’une halle industrielle en marché couvert et ateliers',
    categorie: 'Réhabilitation',
    statut: 'Livré',
    maitriseOuvrage: 'Ville de Saint-Ouen-sur-Seine',
    equipe: ['Atelier Mireille Vasseur', 'Structure : Bollinger + Grohmann', 'Économie : Vanguard', 'Fluides : Alto'],
    texte:
      "La halle de 1928 avait perdu sa toiture mais gardé ses portiques d'acier riveté. Nous les avons conservés tels quels, sablés et repeints en gris chaud, et posé dessus une nouvelle couverture en bacs isolés, percée de sheds orientés au nord. Sous la nef, le marché occupe la travée centrale ; les ateliers d'artisans prennent les bas-côtés derrière des façades en briques de réemploi issues des annexes démolies. Le sol en béton quartzé a été *simplement poncé*. Le projet a coûté un tiers d'une construction neuve équivalente, et surtout, la halle est restée *le repère du quartier* qu'elle était déjà.",
    images: [
      { ratio: '16:9', alt: 'La nef de la halle Saint-Ouen sous les sheds, jour de marché' },
      { ratio: '3:2', alt: 'Portique riveté conservé, peinture gris chaud' },
      { ratio: '4:5', alt: 'Façade d’atelier en briques de réemploi' },
      { ratio: '3:2', alt: 'Angle de la halle depuis la rue, nouvelle couverture' },
      { ratio: '1:1', alt: 'Détail d’assemblage riveté et nouvelle panne' },
      { ratio: '16:9', alt: 'Sol en béton poncé, étals du marché' },
      { ratio: '3:2', alt: 'Bas-côté des ateliers, lumière du nord' },
    ],
    dessins: [
      {
        type: 'plan',
        largeur: 60,
        profondeur: 36,
        murs: [
          [12, 0, 12, 36],
          [48, 0, 48, 36],
          [0, 9, 12, 9],
          [0, 18, 12, 18],
          [0, 27, 12, 27],
          [48, 9, 60, 9],
          [48, 18, 60, 18],
          [48, 27, 60, 27],
        ],
        ouvertures: [[20, 40]],
        legende: 'Plan de la halle, nef et bas-côtés',
      },
      {
        type: 'coupe',
        largeur: 60,
        niveaux: [9.5],
        toit: 'deux-pentes',
        legende: 'Coupe transversale sur les sheds',
      },
    ],
    teinte: 18,
  },
  {
    slug: 'mediatheque-des-tanneurs',
    titre: 'Médiathèque des Tanneurs',
    lieu: 'Rennes',
    annee: 2021,
    surface: 1850,
    programme: 'Médiathèque de quartier et salle de conférence',
    categorie: 'Public',
    statut: 'Livré',
    maitriseOuvrage: 'Rennes Métropole',
    equipe: ['Atelier Mireille Vasseur', 'Structure bois : Gaujard Technologie', 'Acoustique : Peutz'],
    texte:
      "Un bâtiment compact de trois niveaux, en ossature et planchers de bois local, sur un socle en béton bas carbone. La salle de lecture occupe tout le dernier étage sous une toiture à redents qui *découpe la lumière* en bandes régulières. Les rayonnages sont des murs épais : ils portent les planchers et rangent les livres. En rez-de-chaussée, la salle de conférence s'ouvre sur la place par une grande porte coulissante qui transforme le hall en scène de plein air les soirs d'été. La façade en tasseaux de châtaignier non traité grisera avec le temps. Nous voulions une médiathèque qui ressemble à *une grande maison*, pas à un équipement.",
    images: [
      { ratio: '3:2', alt: 'Façade en tasseaux de châtaignier de la médiathèque des Tanneurs' },
      { ratio: '16:9', alt: 'Salle de lecture sous la toiture à redents' },
      { ratio: '4:5', alt: 'Rayonnages porteurs en bois massif' },
      { ratio: '1:1', alt: 'Détail de la porte coulissante sur la place' },
      { ratio: '3:2', alt: 'Hall ouvert sur la place un soir de conférence' },
      { ratio: '4:5', alt: 'Escalier en bois entre les niveaux' },
      { ratio: '16:9', alt: 'La médiathèque depuis la rue des Tanneurs' },
      { ratio: '3:2', alt: 'Espace enfants au premier étage' },
      { ratio: '1:1', alt: 'Assemblage poteau-poutre en bois' },
    ],
    dessins: [
      {
        type: 'plan',
        largeur: 26,
        profondeur: 22,
        murs: [
          [0, 7, 26, 7],
          [0, 14, 26, 14],
          [9, 7, 9, 22],
          [18, 0, 18, 7],
        ],
        ouvertures: [[10, 17]],
        legende: 'Plan du deuxième étage, salle de lecture',
      },
      {
        type: 'coupe',
        largeur: 26,
        niveaux: [4.2, 3.4, 4.6],
        toit: 'mono',
        legende: 'Coupe longitudinale',
      },
    ],
    teinte: 78,
  },
  {
    slug: 'les-terrasses-du-canal',
    titre: 'Les Terrasses du Canal',
    lieu: 'Pantin',
    annee: 2024,
    surface: 5600,
    programme: '48 logements sociaux et deux commerces',
    categorie: 'Logement',
    statut: 'Livré',
    maitriseOuvrage: 'Seine-Saint-Denis Habitat',
    equipe: ['Atelier Mireille Vasseur', 'Structure : EVP', 'Environnement : Franck Boutté', 'Paysage : Wagon Landscaping'],
    texte:
      "Quarante-huit logements le long du canal de l'Ourcq, distribués par des coursives extérieures côté rue et prolongés par des terrasses filantes côté eau. Chaque appartement *traverse* le bâtiment et possède au moins deux orientations. La structure en béton est laissée brute à l'intérieur ; les façades sont en briques moulées main, posées avec un joint creux qui accroche l'ombre. Les commerces au rez-de-chaussée reprennent la hauteur des anciens entrepôts voisins. Un jardin planté en cœur d'îlot recueille les eaux de pluie. Le projet a été livré à un coût de construction inférieur de dix pour cent à la moyenne des opérations comparables, sans renoncer aux *hauteurs sous plafond de 2,70 m*.",
    images: [
      { ratio: '16:9', alt: 'Les Terrasses du Canal depuis la rive opposée de l’Ourcq' },
      { ratio: '4:5', alt: 'Terrasses filantes en façade sur le canal' },
      { ratio: '3:2', alt: 'Coursive extérieure côté rue, briques moulées main' },
      { ratio: '1:1', alt: 'Détail du joint creux entre briques' },
      { ratio: '3:2', alt: 'Séjour traversant, béton brut et menuiseries bois' },
      { ratio: '16:9', alt: 'Jardin en cœur d’îlot après la pluie' },
      { ratio: '4:5', alt: 'Escalier ouvert entre deux coursives' },
      { ratio: '3:2', alt: 'Commerce en rez-de-chaussée, hauteur d’entrepôt' },
    ],
    dessins: [
      {
        type: 'plan',
        largeur: 54,
        profondeur: 14,
        murs: [
          [9, 0, 9, 14],
          [18, 0, 18, 14],
          [27, 0, 27, 14],
          [36, 0, 36, 14],
          [45, 0, 45, 14],
          [0, 3, 54, 3],
        ],
        ouvertures: [[10, 17], [19, 26], [28, 35], [37, 44], [46, 53]],
        legende: 'Plan d’étage courant, six logements traversants',
      },
      {
        type: 'coupe',
        largeur: 14,
        niveaux: [4.5, 2.7, 2.7, 2.7, 2.7, 2.7],
        toit: 'plat',
        enterre: 3,
        legende: 'Coupe transversale, coursive et terrasse',
      },
    ],
    teinte: 8,
  },
  {
    slug: 'extension-aux-lilas',
    titre: 'Extension aux Lilas',
    lieu: 'Les Lilas',
    annee: 2020,
    surface: 64,
    programme: 'Extension bois d’une maison de ville',
    categorie: 'Logement',
    statut: 'Livré',
    maitriseOuvrage: 'Privée',
    equipe: ['Atelier Mireille Vasseur', 'Charpente : Les Ateliers du Bois'],
    texte:
      "Une pièce de plus, sur deux niveaux, accrochée au pignon aveugle d'une maison de 1930. L'ossature en pin douglas a été préfabriquée en atelier et *levée en trois jours*. En bas, une cuisine ouverte sur le jardin par une baie de toute la largeur ; en haut, un bureau sous un toit à une pente dont le débord protège la façade. Le bardage en mélèze brut est posé à claire-voie. L'ancien mur pignon, dégagé de son enduit, reste visible à l'intérieur avec ses briques et ses traces de cheminée. C'est un projet modeste qui a demandé autant de dessins qu'un grand : chaque assemblage devait être *juste du premier coup*.",
    images: [
      { ratio: '4:5', alt: 'Extension bois accrochée au pignon de la maison de 1930' },
      { ratio: '3:2', alt: 'Cuisine ouverte sur le jardin par une baie toute largeur' },
      { ratio: '1:1', alt: 'Détail du bardage mélèze à claire-voie' },
      { ratio: '16:9', alt: 'Bureau sous le toit à une pente' },
      { ratio: '3:2', alt: 'Ancien pignon en briques dégagé, vu de l’intérieur' },
      { ratio: '4:5', alt: 'Levage de l’ossature préfabriquée, jour deux' },
    ],
    dessins: [
      {
        type: 'plan',
        largeur: 8,
        profondeur: 4.5,
        murs: [[3.2, 0, 3.2, 4.5]],
        ouvertures: [[0.4, 7.6]],
        legende: 'Plan du rez-de-chaussée, cuisine et rangement',
      },
      {
        type: 'coupe',
        largeur: 8,
        niveaux: [2.6, 2.5],
        toit: 'mono',
        legende: 'Coupe sur la baie',
      },
    ],
    teinte: 52,
  },
  {
    slug: 'ecole-des-hauts-champs',
    titre: 'École des Hauts-Champs',
    lieu: 'Nantes',
    annee: 2025,
    surface: 3100,
    programme: 'Groupe scolaire de douze classes et restaurant',
    categorie: 'Public',
    statut: 'En chantier',
    maitriseOuvrage: 'Ville de Nantes',
    equipe: ['Atelier Mireille Vasseur', 'Structure : Arcadis', 'Paysage : Phytolab', 'Acoustique : Lasa'],
    texte:
      "Douze classes réparties en trois maisons de plain-pied autour d'une cour plantée, reliées par un préau continu. Chaque maison a *son toit, sa couleur et son jardin*, pour que les enfants s'y repèrent sans plan. Les classes sont traversantes, ventilées naturellement, avec des plafonds hauts en bois apparent. Les murs sont en blocs de terre crue comprimée, fabriqués à vingt kilomètres du site avec les terres du terrassement. Le restaurant scolaire, en tête d'îlot, sert aussi de salle de quartier le soir. Le chantier a commencé en septembre 2024 ; la livraison est prévue pour la rentrée 2026. C'est le premier bâtiment public en *terre crue porteuse* de la métropole.",
    images: [
      { ratio: '16:9', alt: 'Maquette des trois maisons autour de la cour plantée' },
      { ratio: '3:2', alt: 'Chantier, murs en blocs de terre crue en cours de montage' },
      { ratio: '4:5', alt: 'Préau continu en ossature bois, avant couverture' },
      { ratio: '1:1', alt: 'Échantillons de terre crue comprimée' },
      { ratio: '3:2', alt: 'Salle de classe traversante, plafond bois' },
      { ratio: '16:9', alt: 'Vue axonométrique de l’ensemble' },
    ],
    dessins: [
      {
        type: 'plan',
        largeur: 48,
        profondeur: 30,
        murs: [
          [0, 10, 14, 10],
          [7, 0, 7, 10],
          [34, 10, 48, 10],
          [41, 0, 41, 10],
          [0, 20, 48, 20],
          [8, 20, 8, 30],
          [16, 20, 16, 30],
          [24, 20, 24, 30],
          [32, 20, 32, 30],
          [40, 20, 40, 30],
        ],
        ouvertures: [[2, 6], [10, 14], [18, 22], [26, 30], [34, 38], [42, 46]],
        legende: 'Plan masse, trois maisons et préau',
      },
      {
        type: 'coupe',
        largeur: 30,
        niveaux: [3.6],
        toit: 'deux-pentes',
        legende: 'Coupe sur une maison et le préau',
      },
    ],
    teinte: 96,
  },
  {
    slug: 'lumiere-fossile',
    titre: 'Lumière fossile',
    lieu: 'Musée de la Mine, Saint-Étienne',
    annee: 2023,
    surface: 420,
    programme: 'Scénographie d’exposition temporaire',
    categorie: 'Culture',
    statut: 'Livré',
    maitriseOuvrage: 'Musée de la Mine de Saint-Étienne',
    equipe: ['Atelier Mireille Vasseur', 'Lumière : ACL', 'Graphisme : Studio Plastac'],
    texte:
      "Une exposition sur la lumière dans les galeries de mine, du chandelier de terre à la lampe à acétylène. Le parcours descend : le visiteur traverse une succession de *seuils de plus en plus étroits*, du plein jour du hall à une salle éclairée à quatre lux, où les objets sont posés sur des tables en acier noir. Tout le mobilier est démontable et a été réutilisé pour deux autres expositions. Les cloisons sont en panneaux de fibres de bois teintés dans la masse, sans peinture. Nous avons dessiné cette scénographie comme un bâtiment : *une coupe*, un cheminement, des pièces. Trente-deux mille visiteurs en cinq mois.",
    images: [
      { ratio: '3:2', alt: 'Salle sombre de l’exposition Lumière fossile, tables en acier noir' },
      { ratio: '4:5', alt: 'Seuil étroit entre deux salles, panneaux de fibres de bois' },
      { ratio: '16:9', alt: 'Vue d’ensemble du parcours depuis le hall' },
      { ratio: '1:1', alt: 'Lampe à acétylène sous vitrine' },
      { ratio: '3:2', alt: 'Cloisons teintées dans la masse, éclairage rasant' },
      { ratio: '4:5', alt: 'Montage du mobilier démontable' },
    ],
    dessins: [
      {
        type: 'plan',
        largeur: 30,
        profondeur: 14,
        murs: [
          [8, 0, 8, 9],
          [8, 11.5, 8, 14],
          [16, 2.5, 16, 14],
          [16, 0, 16, 1],
          [23, 0, 23, 10],
          [23, 12, 23, 14],
        ],
        ouvertures: [[1, 6]],
        legende: 'Plan du parcours, quatre salles',
      },
      {
        type: 'coupe',
        largeur: 30,
        niveaux: [5.2],
        toit: 'plat',
        legende: 'Coupe longitudinale, seuils décroissants',
      },
    ],
    teinte: 210,
  },
  {
    slug: 'belvedere-du-vercors',
    titre: 'Belvédère du Vercors',
    lieu: 'Villard-de-Lans',
    annee: 2026,
    surface: 210,
    programme: 'Belvédère et refuge d’étape',
    categorie: 'Public',
    statut: 'Étude',
    maitriseOuvrage: 'Parc naturel régional du Vercors',
    equipe: ['Atelier Mireille Vasseur', 'Structure bois : Sylva Conseil'],
    texte:
      "Au bord des falaises, un petit bâtiment sur pilotis qui abrite un refuge de vingt couchages et une terrasse d'observation. Le volume est une *longue boîte de bois* posée perpendiculairement à la pente, dont l'extrémité s'avance de six mètres au-dessus du vide. Les pilotis en mélèze reposent sur des micropieux pour ne pas toucher le sol calcaire. La toiture récupère l'eau de pluie ; un poêle à bois et des panneaux solaires suffisent à l'autonomie. Les éléments sont dimensionnés pour être héliportés. L'étude de faisabilité a été rendue en mars 2026 ; le permis de construire est en cours. Un projet *lent*, comme la montagne le demande.",
    images: [
      { ratio: '16:9', alt: 'Perspective du belvédère en porte-à-faux sur la falaise' },
      { ratio: '4:5', alt: 'Maquette d’étude, pilotis en mélèze' },
      { ratio: '3:2', alt: 'Croquis de la terrasse d’observation' },
      { ratio: '1:1', alt: 'Relevé du site, calcaire et pins' },
      { ratio: '3:2', alt: 'Élévation ouest de l’étude' },
      { ratio: '16:9', alt: 'Vue du site depuis le sentier d’accès' },
    ],
    dessins: [
      {
        type: 'plan',
        largeur: 24,
        profondeur: 6,
        murs: [
          [6, 0, 6, 6],
          [12, 0, 12, 6],
          [18, 0, 18, 6],
        ],
        ouvertures: [[19, 23]],
        legende: 'Plan, dortoirs et terrasse en bout',
      },
      {
        type: 'coupe',
        largeur: 24,
        niveaux: [2.8],
        toit: 'mono',
        legende: 'Coupe longitudinale, porte-à-faux sur la pente',
      },
    ],
    teinte: 150,
  },
]
